RockPaperScissors and DiceRoll games hw4
Mike-Like11/SenlaIOSCourse pull request #4
Opened 2022-03-31 12:21 UTC by Mike-Like11

Иванцов Михаил

2022-04-04 20:45 UTC, igorpenkin requested changes

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/DiceGameViewController.swift
> +    private lazy var verticalStackView:UIStackView = {
Зачем lazy?

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/DiceGameViewController.swift
> +    private lazy var optionsStackView:UIStackView = {
Зачем lazy?

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/DiceGameViewController.swift
> +    private lazy var buttonOptions:[UIImageView] = {
Зачем lazy?

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/DiceGameViewController.swift
> +    private lazy var chosenStackView2:UIStackView = {
Зачем lazy?

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/DiceGameViewController.swift
> +    func Roll(){
если внутри кейсов свитча идет какая то не линейная логика на 3+ строк надо выносить это в методы

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/DiceGameViewController.swift
> +            buttonOptions.forEach { image in
нецелесообразно хранить картинки в массиве, так как каждый раз тебе приходится пробегаться по массиву, переделай

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/DiceGameViewController.swift
> +        verticalStackView.frame = self.view.bounds.insetBy(dx: 20, dy: 200)
Фрейм должен задаваться строго в методе viewDidLayoutSubviews()

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/DiceGameViewController.swift
> +        for i in 0...5{
0...5 не хорошая тема, в случае с массивом подумай как пробежаться по контейнеру безопасно, иначе если вдруг у тебя кол-во элементов будет не 6 то приложение упадет

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +protocol RockPaperScissorsable: AnyObject {
```suggestion
protocol SettingsViewControllerDelegate: AnyObject {
```

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    var resultOptions:[(String,String)] = [("",""),("Поражение","Lose"),("Ничья","Draw"),("Победа","Victory")]
Хранить массив туплсов не очень идея, а если тебе потом придется расширить словарь переводов или использовать его где то на другом экране? плюс зачем тебе вообще элемент ("",""). ? или это смайлик совы?)

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    var playMode: Bool = false
Что за плей мод? нейминг должен быть говорящим и всегда должен быть заложен под масштабируемость, а если завтра тебе скажут что в игре должно быть 3 или 100500 модов? Enum в помощь

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    private lazy var yourChoosenImage:UIImageView = {
зачем lazy?

2022-04-04 20:45 UTC, igrpnkn commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    private lazy var opponentChoosenImage:UIImageView = {
зачем lazy?

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    private lazy var buttonOptions:[UIButton] = {
зачем lazy?

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +            button.addTarget(self, action: #selector(RockPaperScissorsViewController.makeMove(_:)), for: .touchUpInside)
А почему здесь решил использовать селекторы?

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    private lazy var buttonOptions:[UIButton] = {
Массив кнопок не очень удачное решение

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    private lazy var imageOptions:[UIImage] = []
Хранить массив картинок не очень хорошее решение, ты можешь хранить массив путей к этим картинкам, или вообще обойтись енамом

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    private lazy var verticalStackView:UIStackView = {
зачем lazy?

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    private lazy var optionsStackView:UIStackView = {
зачем lazy?

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    private lazy var chosenStackView2:UIStackView = {
зачем lazy?

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    private lazy var resultLabel: UILabel = {
зачем lazy?

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +        verticalStackView.frame = self.view.bounds.insetBy(dx: 20, dy: 200)
фреймы должны задаваться строго во viewDidLayoutSubviews() и уж точно не через insetBy().
self в этой строчке не нужен.

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +extension RockPaperScissorsViewController{
расширение следует сделать приватным

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +                self.resultLabel.isHidden = false
в блоке анимации должны анимироваться сами UI параметры, никакой логики тут быть не должно

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +                self.resultLabel.isHidden = false
все If блоки и вызовы других методов выноси отсюда

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
async блок здесь не нужен, у тебя есть в анимации параметр delay

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +        buttonOptions.forEach { button in
```suggestion
        buttonOptions.forEach { $0.isEnabled = true }
```

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +        buttonOptions.forEach { button in
А вообще зачем ты ставишь им этот статус? ты потом их по нему нигде не мапишь

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +        if let image = UIImage(named: "Rock"){
Этот анвраппинг тут не нужен, у UIImageView поле image и так опциональное

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +    func setupLangResult(){
Свитчевать или делать через If не очень хорошо, так как поддержка кода становится затруднительней. 
Подумай как тут обойтись с помощью структур и протокола.
В принципе механика игры не должна знать о том что меняется язык, она должна брать текст из одного места и того же места, при смене языка ты лишь подменяешь словарь (структуру, не dictionary)

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +protocol RockPaperScissorsable: AnyObject {
Этот протокол должен описывать поведение делегата экрана SettingsViewController и лежать в одном файле с ним.
Это все в нем быть не должно:
     func changeResult(result:Result)
     var playMode:Bool { get set }
     var lang:Lang {get set}
     var result:Result {get set}
     
     Экран настроек не должен знать что происходит в процессе игры на экране игры, он должен только передавать сами изменения настроек

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/SettingsViewController.swift
> +        if let delegate = delegate {
Этой логики тут быть не должно, экран настроек должен получать необходимые параметры либо при инициализации, либо иметь публичные проперти которые будет сеттить владелец жатого экрана

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/SettingsViewController.swift
> +
Лишние отступы строк тут не нужны

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/SettingsViewController.swift
> +    private lazy var modeLabel:UILabel = {
зачем lazy?

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/SettingsViewController.swift
> +        if let delegate = delegate {
Этой логики тут быть не должно

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/SettingsViewController.swift
> +    private lazy var langLabel:UILabel = {
Зачем lazy?

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/SettingsViewController.swift
> +        langLabel.translatesAutoresizingMaskIntoConstraints = false
Конкуренты не должны задаваться здесь, так как этот метод вызывается много раз подряд и ты каждый раз сеттишь и активируешь констрейнты.
Убирай это от сюда

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/SettingsViewController.swift
> +    @objc func segmentedValueChanged(_ sender:UISegmentedControl!) {
```suggestion
    @objc func segmentedValueChanged(_ sender:UISegmentedControl) {
```

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/SettingsViewController.swift
> +    @objc func switchStateDidChange(_ sender:UISwitch!){
```suggestion
    @objc func switchStateDidChange(_ sender: UISwitch) {
```

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/SettingsViewController.swift
> +        switch sender.selectedSegmentIndex{
было бы лучше свитчить Enum

2022-04-04 20:45 UTC, igorpenkin commented on hw4/SimpleIOSGames/SimpleIOSGames/ViewController.swift
> +class ViewController: UIViewController {
А зачем тебе этот пустой ViewController?

2022-04-06 09:35 UTC, Mike-Like11 commented on hw4/SimpleIOSGames/SimpleIOSGames/RockPaperScissorsViewController.swift
> +            button.addTarget(self, action: #selector(RockPaperScissorsViewController.makeMove(_:)), for: .touchUpInside)
Чтобы передать саму кнопку в функцию, без селектора не получалось

2022-04-06 20:55 UTC, igorpenkin approved these changes

2022-04-06 21:17 UTC, merged